# Bird Monitoring Pipeline Configuration
# macOS Local Development Settings

# Environment settings
environment: development
project_root: .

# Directories
models_dir: models
data_dir: data
logs_dir: logs

# Model paths (update these when models are available)
birdnet_model_path: null
yolo_model_path: null
transfg_model_path: null

# Audio processing settings
audio_segment_length: 3.0
audio_overlap: 0.5
audio_sample_rate: 22050
audio_confidence_threshold: 0.3

# Video processing settings
video_frame_skip: 1
video_resize_height: null
video_confidence_threshold: 0.5

# Species classification
species_confidence_threshold: 0.6

# Temporal correlation
temporal_correlation_window: 2.0

# Confidence scoring
audio_only_base_confidence: 0.3
video_only_base_confidence: 0.4
audio_video_base_confidence: 0.7

# Web application
web_host: localhost
web_port: 8000
web_reload: true

# Logging
log_level: INFO
log_format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Performance
max_workers: 4
batch_size: 16
gpu_enabled: true